language: cpp

compiler:
-gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
  
install:
  # install g++ 6, if tests are run with g++
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-6; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50; fi

  
script:
- cd Tests
- make
- if [ "`echo $CXX`" == "g++" ]; then ./a.out; fi
